name: lecture-env
channels:
    - conda-forge
dependencies:
    - python
    - numpy
    - jupyter
    - jupytext
    - rise
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - pandas
    - nbconvert
    - regex
    - pip:
        - cite2c
        - nltk
        - langdetect
        - chardet
        - stanfordnlp
